//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseTran
    {
        public int Id { get; set; }
        public int ExpTypeId { get; set; }
        public System.DateTime PostingDate { get; set; }
        public decimal Amount { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Description { get; set; }
    
        public virtual ExpenseType ExpenseType { get; set; }
    }
}
