//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRole()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
        public int Role1 { get; set; }
        public int Role2 { get; set; }
        public int Role3 { get; set; }
        public int Role4 { get; set; }
        public int Role5 { get; set; }
        public int Role6 { get; set; }
        public int Role7 { get; set; }
        public int Role8 { get; set; }
        public int Role9 { get; set; }
        public int Role10 { get; set; }
        public int Role11 { get; set; }
        public int Role12 { get; set; }
        public int Role13 { get; set; }
        public int Role14 { get; set; }
        public int Role15 { get; set; }
        public int Role16 { get; set; }
        public int Role17 { get; set; }
        public int Role18 { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
